

# CRISP theme

logo: /images/profile.png
rss: /atom.xml
disqus: mahesh8488-github-io
google_analytics: UA-28385202-1

# Social accounts
instagram:
pinterest:
github: http://github.com/mahesh8488
facebook: http://facebook.com/mahesh8488
twitter: http://twitter.com/mahesh8488
linkedin: http://linkedin.com/in/mahesh-alwani-0487b8104